version: "3"

services:
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    command: npm start
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./ui:/app
    stdin_open: true

    